name: file_list_previewer
description: A flutter package for viewing all files.
version: 0.0.1
author: WalkingTree Technologies<support@walkingtree.tech>
homepage: https://github.com/abhilashahyd/file_list_previewer



environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  open_file: ^3.0.1
  url_launcher: ^5.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   assets:

    - assets/images/video.png
