name: file_list_previewer
description: A flutter package for viewing a list of local files in the form of clickable thumbnails.
version: 0.0.2
author: WalkingTree Technologies<support@walkingtree.tech>
homepage: https://github.com/walkingtree/file_list_previewer



environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  open_file: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   assets:

    - assets/images/video.png
